version: "3.8"

services:
  # Service untuk database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password # GANTI DENGAN PASSWORD ANDA
      MYSQL_DATABASE: mydatabase # Nama database yang akan dibuat otomatis
      MYSQL_USER: myuser # User baru yang akan dibuat
      MYSQL_PASSWORD: your_strong_user_password # GANTI DENGAN PASSWORD ANDA
    volumes:
      - db_data:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-ui
    restart: always
    environment:
      PMA_HOST: db
      # uri_anda_disini diatur sesuai IP Anda
      PMA_ABSOLUTE_URI: http://uri_anda_disini/phpmyadmin/
    depends_on:
      - db

  # Service untuk Nginx sebagai Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      # Memuat file konfigurasi Nginx dari folder ./nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpmyadmin

volumes:
  db_data:
