version: "3.8"

services:
  # Service untuk database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # "HOST_PORT:CONTAINER_PORT"
    volumes:
      - db_data:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"

  # Service untuk phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-ui
    restart: always
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: http://${PMA_DOMAIN}/phpmyadmin/
    volumes:
      - ./phpmyadmin-config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db

  # Service untuk Nginx
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpmyadmin

volumes:
  db_data:
